name: Build
on: [push, pull_request]
jobs:
    unit-tests:
        name: unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v2.1.1
              with:
                  node-version: 12.18.3
            - name: Install node.js packages
              run: npm install
            - name: Run generator tests
              run: npm test
